[INFO] 2024-04-15 09:42:43.654 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.659 +0800 - *********************************  Initialize task context  ***********************************
[INFO] 2024-04-15 09:42:43.659 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.659 +0800 - Begin to initialize task
[INFO] 2024-04-15 09:42:43.660 +0800 - Set task startTime: 1713145363660
[INFO] 2024-04-15 09:42:43.660 +0800 - Set task appId: 274_547
[INFO] 2024-04-15 09:42:43.661 +0800 - End initialize task {
  "taskInstanceId" : 547,
  "taskName" : "spark_shell",
  "firstSubmitTime" : 1713145363638,
  "startTime" : 1713145363660,
  "taskType" : "SHELL",
  "workflowInstanceHost" : "172.18.0.3:5678",
  "host" : "172.18.0.7:1234",
  "logPath" : "/opt/dolphinscheduler/logs/20240415/13201021801792/17/274/547.log",
  "processId" : 0,
  "processDefineCode" : 13201021801792,
  "processDefineVersion" : 17,
  "processInstanceId" : 274,
  "scheduleTime" : 0,
  "executorId" : 1,
  "cmdTypeIfComplement" : 0,
  "tenantCode" : "default",
  "processDefineId" : 0,
  "projectId" : 0,
  "projectCode" : 13010050770016,
  "taskParams" : "{\"localParams\":[],\"rawScript\":\"$SPARK_HOME/bin/spark-submit \\\\\\n    --master spark://spark-master:7077 \\\\\\n    --conf spark.driver.cores=1 \\\\\\n    --conf spark.driver.memory=512M \\\\\\n    --conf spark.executor.instances=2 \\\\\\n    --conf spark.executor.cores=2 \\\\\\n    --conf spark.executor.memory=1G \\\\\\n    --name myapple spark-test.py\\n\",\"resourceList\":[{\"id\":null,\"resourceName\":\"file:/dolphinscheduler/default/resources/spark-test.py\",\"res\":null}]}",
  "environmentConfig" : "export SPARK_HOME=/opt/spark-3.5.1-bin-hadoop3\nexport JAVA_HOME=/opt/java/openjdk\nexport HADOOP_CONF_DIR=/opt/hadoop-3.4.0/etc/hadoop\nexport PYSPARK_PYTHON=/bin/python3.11",
  "prepareParamsMap" : {
    "system.task.definition.name" : {
      "prop" : "system.task.definition.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "spark_shell"
    },
    "system.project.name" : {
      "prop" : "system.project.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : null
    },
    "system.project.code" : {
      "prop" : "system.project.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "13010050770016"
    },
    "system.workflow.instance.id" : {
      "prop" : "system.workflow.instance.id",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "274"
    },
    "system.biz.curdate" : {
      "prop" : "system.biz.curdate",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20240415"
    },
    "system.biz.date" : {
      "prop" : "system.biz.date",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20240414"
    },
    "system.task.instance.id" : {
      "prop" : "system.task.instance.id",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "547"
    },
    "system.workflow.definition.name" : {
      "prop" : "system.workflow.definition.name",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "spark"
    },
    "system.task.definition.code" : {
      "prop" : "system.task.definition.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "13210058002752"
    },
    "system.workflow.definition.code" : {
      "prop" : "system.workflow.definition.code",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "13201021801792"
    },
    "system.datetime" : {
      "prop" : "system.datetime",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "20240415094243"
    }
  },
  "taskAppId" : "274_547",
  "taskTimeout" : 2147483647,
  "workerGroup" : "default",
  "delayTime" : 0,
  "currentExecutionStatus" : "SUBMITTED_SUCCESS",
  "endTime" : 0,
  "dryRun" : 0,
  "paramsMap" : { },
  "cpuQuota" : -1,
  "memoryMax" : -1,
  "testFlag" : 0,
  "logBufferEnable" : false,
  "dispatchFailTimes" : 0
}
[INFO] 2024-04-15 09:42:43.662 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.662 +0800 - *********************************  Load task instance plugin  *********************************
[INFO] 2024-04-15 09:42:43.663 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.669 +0800 - Send task status RUNNING_EXECUTION master: 172.18.0.7:1234
[INFO] 2024-04-15 09:42:43.670 +0800 - TenantCode: default check successfully
[INFO] 2024-04-15 09:42:43.671 +0800 - WorkflowInstanceExecDir: /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547 check successfully
[INFO] 2024-04-15 09:42:43.671 +0800 - Create TaskChannel: org.apache.dolphinscheduler.plugin.task.shell.ShellTaskChannel successfully
[INFO] 2024-04-15 09:42:43.674 +0800 - Download resources successfully: 
ResourceContext(resourceItemMap={file:/dolphinscheduler/default/resources/spark-test.py=ResourceContext.ResourceItem(resourceAbsolutePathInStorage=file:/dolphinscheduler/default/resources/spark-test.py, resourceRelativePath=spark-test.py, resourceAbsolutePathInLocal=/tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py)})
[INFO] 2024-04-15 09:42:43.674 +0800 - Download upstream files: [] successfully
[INFO] 2024-04-15 09:42:43.675 +0800 - Task plugin instance: SHELL create successfully
[INFO] 2024-04-15 09:42:43.675 +0800 - Initialize shell task params {
  "localParams" : [ ],
  "varPool" : null,
  "rawScript" : "$SPARK_HOME/bin/spark-submit \\\n    --master spark://spark-master:7077 \\\n    --conf spark.driver.cores=1 \\\n    --conf spark.driver.memory=512M \\\n    --conf spark.executor.instances=2 \\\n    --conf spark.executor.cores=2 \\\n    --conf spark.executor.memory=1G \\\n    --name myapple spark-test.py\n",
  "resourceList" : [ {
    "id" : null,
    "resourceName" : "file:/dolphinscheduler/default/resources/spark-test.py",
    "res" : null
  } ]
}
[INFO] 2024-04-15 09:42:43.675 +0800 - Success initialized task plugin instance successfully
[INFO] 2024-04-15 09:42:43.675 +0800 - Set taskVarPool: null successfully
[INFO] 2024-04-15 09:42:43.676 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.676 +0800 - *********************************  Execute task instance  *************************************
[INFO] 2024-04-15 09:42:43.676 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:42:43.677 +0800 - Final Shell file is: 
[INFO] 2024-04-15 09:42:43.677 +0800 - ****************************** Script Content *****************************************************************
[INFO] 2024-04-15 09:42:43.677 +0800 - #!/bin/bash
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
export SPARK_HOME=/opt/spark-3.5.1-bin-hadoop3
export JAVA_HOME=/opt/java/openjdk
export HADOOP_CONF_DIR=/opt/hadoop-3.4.0/etc/hadoop
export PYSPARK_PYTHON=/bin/python3.11
$SPARK_HOME/bin/spark-submit \
    --master spark://spark-master:7077 \
    --conf spark.driver.cores=1 \
    --conf spark.driver.memory=512M \
    --conf spark.executor.instances=2 \
    --conf spark.executor.cores=2 \
    --conf spark.executor.memory=1G \
    --name myapple spark-test.py

[INFO] 2024-04-15 09:42:43.677 +0800 - ****************************** Script Content *****************************************************************
[INFO] 2024-04-15 09:42:43.678 +0800 - Executing shell command : sudo -u default -i /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/274_547.sh
[INFO] 2024-04-15 09:42:43.687 +0800 - process start, process id is: 1826
[INFO] 2024-04-15 09:42:44.690 +0800 -  -> 
	sudo: unable to change directory to /home/default: No such file or directory
[INFO] 2024-04-15 09:42:50.721 +0800 -  -> 
	24/04/15 09:42:50 INFO SparkContext: Running Spark version 3.5.1
	24/04/15 09:42:50 INFO SparkContext: OS info Linux, 6.5.0-27-generic, amd64
	24/04/15 09:42:50 INFO SparkContext: Java version 1.8.0_402
[INFO] 2024-04-15 09:42:51.722 +0800 -  -> 
	24/04/15 09:42:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
	24/04/15 09:42:51 INFO ResourceUtils: ==============================================================
	24/04/15 09:42:51 INFO ResourceUtils: No custom resources configured for spark.driver.
	24/04/15 09:42:51 INFO ResourceUtils: ==============================================================
	24/04/15 09:42:51 INFO SparkContext: Submitted application: My App
	24/04/15 09:42:51 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 2, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
	24/04/15 09:42:51 INFO ResourceProfile: Limiting resource is cpus at 2 tasks per executor
	24/04/15 09:42:51 INFO ResourceProfileManager: Added ResourceProfile id: 0
	24/04/15 09:42:51 INFO SecurityManager: Changing view acls to: default
	24/04/15 09:42:51 INFO SecurityManager: Changing modify acls to: default
	24/04/15 09:42:51 INFO SecurityManager: Changing view acls groups to: 
	24/04/15 09:42:51 INFO SecurityManager: Changing modify acls groups to: 
	24/04/15 09:42:51 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[INFO] 2024-04-15 09:42:52.725 +0800 -  -> 
	24/04/15 09:42:52 INFO Utils: Successfully started service 'sparkDriver' on port 36847.
	24/04/15 09:42:52 INFO SparkEnv: Registering MapOutputTracker
	24/04/15 09:42:52 INFO SparkEnv: Registering BlockManagerMaster
[INFO] 2024-04-15 09:42:53.727 +0800 -  -> 
	24/04/15 09:42:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
	24/04/15 09:42:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
	24/04/15 09:42:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
	24/04/15 09:42:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-1000b317-3ad8-499c-bb96-e9ef048aadf6
	24/04/15 09:42:52 INFO MemoryStore: MemoryStore started with capacity 93.3 MiB
	24/04/15 09:42:52 INFO SparkEnv: Registering OutputCommitCoordinator
	24/04/15 09:42:53 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
	24/04/15 09:42:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[INFO] 2024-04-15 09:42:54.730 +0800 -  -> 
	24/04/15 09:42:54 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
	24/04/15 09:42:54 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 117 ms (0 ms spent in bootstraps)
	24/04/15 09:42:54 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240415014254-0005
	24/04/15 09:42:54 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240415014254-0005/0 on worker-20240415002944-172.18.0.6-35429 (172.18.0.6:35429) with 2 core(s)
	24/04/15 09:42:54 INFO StandaloneSchedulerBackend: Granted executor ID app-20240415014254-0005/0 on hostPort 172.18.0.6:35429 with 2 core(s), 1024.0 MiB RAM
	24/04/15 09:42:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40063.
	24/04/15 09:42:54 INFO NettyBlockTransferService: Server created on 79bef8694a77:40063
	24/04/15 09:42:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
	24/04/15 09:42:54 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240415014254-0005/0 is now RUNNING
	24/04/15 09:42:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 79bef8694a77, 40063, None)
	24/04/15 09:42:54 INFO BlockManagerMasterEndpoint: Registering block manager 79bef8694a77:40063 with 93.3 MiB RAM, BlockManagerId(driver, 79bef8694a77, 40063, None)
[INFO] 2024-04-15 09:42:55.734 +0800 -  -> 
	24/04/15 09:42:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 79bef8694a77, 40063, None)
	24/04/15 09:42:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 79bef8694a77, 40063, None)
[INFO] 2024-04-15 09:42:57.738 +0800 -  -> 
	24/04/15 09:42:57 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[INFO] 2024-04-15 09:43:01.747 +0800 -  -> 
	24/04/15 09:43:01 INFO SparkContext: Starting job: sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12
[INFO] 2024-04-15 09:43:02.754 +0800 -  -> 
	24/04/15 09:43:01 INFO DAGScheduler: Got job 0 (sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12) with 2 output partitions
	24/04/15 09:43:01 INFO DAGScheduler: Final stage: ResultStage 0 (sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12)
	24/04/15 09:43:01 INFO DAGScheduler: Parents of final stage: List()
	24/04/15 09:43:01 INFO DAGScheduler: Missing parents: List()
	24/04/15 09:43:01 INFO DAGScheduler: Submitting ResultStage 0 (PythonRDD[1] at sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12), which has no missing parents
[INFO] 2024-04-15 09:43:03.760 +0800 -  -> 
	24/04/15 09:43:03 INFO AsyncEventQueue: Process of event SparkListenerJobStart(0,1713145381806,WrappedArray(org.apache.spark.scheduler.StageInfo@5fd890c1),{callSite.short=sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12, spark.rdd.scope.noOverride=true, spark.rdd.scope={"id":"1","name":"collect"}}) by listener AppStatusListener took 1.445118794s.
	24/04/15 09:43:03 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 8.1 KiB, free 93.3 MiB)
	24/04/15 09:43:03 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 5.1 KiB, free 93.3 MiB)
	24/04/15 09:43:03 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 79bef8694a77:40063 (size: 5.1 KiB, free: 93.3 MiB)
	24/04/15 09:43:03 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[INFO] 2024-04-15 09:43:04.763 +0800 -  -> 
	24/04/15 09:43:03 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (PythonRDD[1] at sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12) (first 15 tasks are for partitions Vector(0, 1))
	24/04/15 09:43:03 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[INFO] 2024-04-15 09:43:08.766 +0800 -  -> 
	24/04/15 09:43:08 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.6:34446) with ID 0,  ResourceProfileId 0
[INFO] 2024-04-15 09:43:09.768 +0800 -  -> 
	24/04/15 09:43:09 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.6:43471 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.6, 43471, None)
	24/04/15 09:43:09 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:09 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 7599 bytes) 
[INFO] 2024-04-15 09:43:10.771 +0800 -  -> 
	24/04/15 09:43:10 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.6:43471 (size: 5.1 KiB, free: 434.4 MiB)
[INFO] 2024-04-15 09:43:11.772 +0800 -  -> 
	24/04/15 09:43:11 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1) (172.18.0.6 executor 0): java.io.IOException: Cannot run program "/bin/python3.11": error=2, No such file or directory
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
		at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:239)
		at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:139)
		at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:107)
		at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:124)
		at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:174)
		at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
		at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
		at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
		at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
		at org.apache.spark.scheduler.Task.run(Task.scala:141)
		at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:840)
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
		at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
		... 20 more
	
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 1.1 in stage 0.0 (TID 2) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 1]
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 3) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 1.1 in stage 0.0 (TID 2) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 2]
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 1.2 in stage 0.0 (TID 4) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 3) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 3]
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 5) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 5) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 4]
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 1.2 in stage 0.0 (TID 4) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 5]
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 1.3 in stage 0.0 (TID 6) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 7) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 7599 bytes) 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 7) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 6]
	24/04/15 09:43:11 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
	24/04/15 09:43:11 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
	24/04/15 09:43:11 INFO TaskSetManager: Lost task 1.3 in stage 0.0 (TID 6) on 172.18.0.6, executor 0: java.io.IOException (Cannot run program "/bin/python3.11": error=2, No such file or directory) [duplicate 7]
	24/04/15 09:43:11 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
	24/04/15 09:43:11 INFO TaskSchedulerImpl: Cancelling stage 0
	24/04/15 09:43:11 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7) (172.18.0.6 executor 0): java.io.IOException: Cannot run program "/bin/python3.11": error=2, No such file or directory
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
		at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:239)
		at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:139)
		at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:107)
		at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:124)
		at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:174)
		at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
		at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
		at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
		at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
		at org.apache.spark.scheduler.Task.run(Task.scala:141)
		at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:840)
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
		at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
		... 20 more
	
	Driver stacktrace:
	24/04/15 09:43:11 INFO DAGScheduler: ResultStage 0 (sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12) failed in 9.326 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7) (172.18.0.6 executor 0): java.io.IOException: Cannot run program "/bin/python3.11": error=2, No such file or directory
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
		at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:239)
		at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:139)
		at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:107)
		at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:124)
		at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:174)
		at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
		at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
		at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
		at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
		at org.apache.spark.scheduler.Task.run(Task.scala:141)
		at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:840)
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
		at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
		... 20 more
	
	Driver stacktrace:
	24/04/15 09:43:11 INFO DAGScheduler: Job 0 failed: sum at /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py:12, took 10.280190 s
[INFO] 2024-04-15 09:43:12.779 +0800 -  -> 
	Traceback (most recent call last):
	  File "/tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547/spark-test.py", line 12, in <module>
	    print("THE SUM IS HERE: ", rdd.sum())
	                               ^^^^^^^^^
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/rdd.py", line 2291, in sum
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/rdd.py", line 2044, in fold
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/rdd.py", line 1833, in collect
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
	  File "/opt/spark-3.5.1-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
	py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
	: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7) (172.18.0.6 executor 0): java.io.IOException: Cannot run program "/bin/python3.11": error=2, No such file or directory
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
		at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:239)
		at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:139)
		at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:107)
		at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:124)
		at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:174)
		at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
		at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
		at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
		at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
		at org.apache.spark.scheduler.Task.run(Task.scala:141)
		at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:840)
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
		at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
		... 20 more
	
	Driver stacktrace:
		at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
		at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
		at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
		at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
		at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
		at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
		at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
		at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
		at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
		at scala.Option.foreach(Option.scala:407)
		at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
		at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
		at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
		at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
		at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
		at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
		at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
		at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
		at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
		at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
		at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)
		at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
		at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
		at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
		at org.apache.spark.rdd.RDD.collect(RDD.scala:1048)
		at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:195)
		at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
		at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
		at py4j.Gateway.invoke(Gateway.java:282)
		at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
		at py4j.commands.CallCommand.execute(CallCommand.java:79)
		at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
		at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: java.io.IOException: Cannot run program "/bin/python3.11": error=2, No such file or directory
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
		at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:239)
		at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:139)
		at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:107)
		at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:124)
		at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:174)
		at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
		at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
		at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
		at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
		at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
		at org.apache.spark.scheduler.Task.run(Task.scala:141)
		at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
		at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
		at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
		at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.lang.Thread.run(Thread.java:840)
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
		at java.lang.ProcessImpl.start(ProcessImpl.java:244)
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
		... 20 more
	
	24/04/15 09:43:12 INFO SparkContext: Invoking stop() from shutdown hook
	24/04/15 09:43:12 INFO SparkContext: SparkContext is stopping with exitCode 0.
	24/04/15 09:43:12 INFO SparkUI: Stopped Spark web UI at http://79bef8694a77:4040
	24/04/15 09:43:12 INFO StandaloneSchedulerBackend: Shutting down all executors
	24/04/15 09:43:12 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
	24/04/15 09:43:12 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[INFO] 2024-04-15 09:43:13.789 +0800 -  -> 
	24/04/15 09:43:12 INFO MemoryStore: MemoryStore cleared
	24/04/15 09:43:12 INFO BlockManager: BlockManager stopped
	24/04/15 09:43:12 INFO BlockManagerMaster: BlockManagerMaster stopped
	24/04/15 09:43:13 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
	24/04/15 09:43:13 INFO SparkContext: Successfully stopped SparkContext
	24/04/15 09:43:13 INFO ShutdownHookManager: Shutdown hook called
	24/04/15 09:43:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-0e5cd999-b138-4b81-8029-76e0f0031a48
	24/04/15 09:43:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-83ca0e4b-e1f3-45c6-afa2-cf6b11bd3ca9
	24/04/15 09:43:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-83ca0e4b-e1f3-45c6-afa2-cf6b11bd3ca9/pyspark-188085f6-c136-483e-8e2d-ce746bc6aff8
[INFO] 2024-04-15 09:43:13.791 +0800 - process has exited. execute path:/tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547, processId:1826 ,exitStatusCode:1 ,processWaitForStatus:true ,processExitValue:1
[INFO] 2024-04-15 09:43:13.794 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:43:13.795 +0800 - *********************************  Finalize task instance  ************************************
[INFO] 2024-04-15 09:43:13.795 +0800 - ***********************************************************************************************
[INFO] 2024-04-15 09:43:13.795 +0800 - Upload output files: [] successfully
[INFO] 2024-04-15 09:43:13.802 +0800 - Send task execute status: FAILURE to master : 172.18.0.7:1234
[INFO] 2024-04-15 09:43:13.803 +0800 - Remove the current task execute context from worker cache
[INFO] 2024-04-15 09:43:13.803 +0800 - The current execute mode isn't develop mode, will clear the task execute file: /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547
[INFO] 2024-04-15 09:43:13.804 +0800 - Success clear the task execute file: /tmp/dolphinscheduler/exec/process/default/13010050770016/13201021801792_17/274/547
[INFO] 2024-04-15 09:43:13.804 +0800 - FINALIZE_SESSION
