[WI-0][TI-0] - [ERROR] 2024-05-07 17:00:00.372 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:02.205 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:00:02.251 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:07.240 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:09.358 +0800 o.a.d.s.m.s.MasterFailoverService:[86] - Master failover service 172.18.0.14:5678 begin to failover hosts:[172.18.0.14:5678]
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[124] - Master[172.18.0.14:5678] failover starting there are 4 workflowInstance may need to failover, will do a deep check, workflowInstanceIds: [448, 508, 510, 511]
[WI-448][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-448][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-508][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-508][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-510][TI-0] - [INFO] 2024-05-07 17:00:09.386 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-510][TI-0] - [INFO] 2024-05-07 17:00:09.387 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-511][TI-0] - [INFO] 2024-05-07 17:00:09.387 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-511][TI-0] - [INFO] 2024-05-07 17:00:09.387 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:09.387 +0800 o.a.d.s.m.s.MasterFailoverService:[148] - Master[172.18.0.14:5678] failover finished, useTime:4ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:12.251 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:17.266 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:22.281 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:27.335 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:32.367 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:37.379 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:42.403 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:47.432 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-1108][TI-4009] - [INFO] 2024-05-07 17:00:51.942 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [WARN] 2024-05-07 17:00:51.942 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:52.463 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:00:57.488 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:02.506 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:07.529 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:01:10.290 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:12.542 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:17.563 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:22.578 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:27.604 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:32.626 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:37.644 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1101][TI-4002] - [INFO] 2024-05-07 17:01:41.096 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [WARN] 2024-05-07 17:01:41.096 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:42.663 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:47.679 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1106][TI-4007] - [INFO] 2024-05-07 17:01:49.125 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [WARN] 2024-05-07 17:01:49.125 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:52.695 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:01:57.716 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:02.734 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:07.760 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:12.774 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:17.818 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 18/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:02:18.370 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:22.849 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:27.875 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:32.914 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:37.935 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:42.954 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1107][TI-4008] - [INFO] 2024-05-07 17:02:46.267 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [WARN] 2024-05-07 17:02:46.267 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-1103][TI-4004] - [INFO] 2024-05-07 17:02:47.273 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-0][TI-0] - [WARN] 2024-05-07 17:02:47.274 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-1105][TI-4005] - [INFO] 2024-05-07 17:02:47.276 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-0][TI-0] - [WARN] 2024-05-07 17:02:47.277 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-1104][TI-4006] - [INFO] 2024-05-07 17:02:47.279 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [WARN] 2024-05-07 17:02:47.280 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:47.971 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:52.992 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:02:58.007 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:03.019 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:08.041 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:13.057 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:18.068 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:23.093 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:03:26.426 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:28.120 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:33.145 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:38.165 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1102][TI-4003] - [INFO] 2024-05-07 17:03:39.445 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [WARN] 2024-05-07 17:03:39.446 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:43.178 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:48.193 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:53.224 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:03:58.266 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:04:00.379 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:03.284 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:08.297 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:13.317 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:18.335 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:18.636 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0052910052910053 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:04:18.637 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:23.354 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:28.382 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:33.403 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:04:34.485 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:38.418 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-1100][TI-4001] - [INFO] 2024-05-07 17:04:42.694 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [WARN] 2024-05-07 17:04:42.695 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:43.445 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:48.481 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:53.501 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1111][TI-4011] - [INFO] 2024-05-07 17:04:57.719 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-0][TI-0] - [WARN] 2024-05-07 17:04:57.720 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-0][TI-0] - [INFO] 2024-05-07 17:04:58.612 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-1109][TI-4010] - [INFO] 2024-05-07 17:04:58.850 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-0][TI-0] - [WARN] 2024-05-07 17:04:58.852 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-1110][TI-4012] - [INFO] 2024-05-07 17:04:58.856 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [WARN] 2024-05-07 17:04:58.857 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:03.639 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:08.656 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:13.673 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:18.695 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:23.715 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 5/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:28.743 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:33.767 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:38.791 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:05:42.560 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:43.805 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:48.824 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1108][TI-4009] - [INFO] 2024-05-07 17:05:52.011 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [WARN] 2024-05-07 17:05:52.012 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:53.836 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:58.057 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:05:58.863 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:03.878 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:08.899 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:13.915 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:18.931 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:23.946 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:28.960 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:33.990 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:39.010 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1101][TI-4002] - [INFO] 2024-05-07 17:06:41.163 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [WARN] 2024-05-07 17:06:41.165 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:44.033 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:49.056 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1106][TI-4007] - [INFO] 2024-05-07 17:06:49.178 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [WARN] 2024-05-07 17:06:49.179 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [ERROR] 2024-05-07 17:06:50.618 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:54.074 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:06:59.105 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:04.122 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:09.140 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:14.153 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:19.653 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:19.657 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:07:19.668 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:19.699 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:24.722 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:29.733 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:34.756 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:39.772 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:44.787 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1107][TI-4008] - [INFO] 2024-05-07 17:07:46.706 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [WARN] 2024-05-07 17:07:46.707 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-1103][TI-4004] - [INFO] 2024-05-07 17:07:47.709 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-0][TI-0] - [WARN] 2024-05-07 17:07:47.710 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-1105][TI-4005] - [INFO] 2024-05-07 17:07:47.713 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-0][TI-0] - [WARN] 2024-05-07 17:07:47.714 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-1104][TI-4006] - [INFO] 2024-05-07 17:07:47.715 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [WARN] 2024-05-07 17:07:47.716 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:49.802 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:07:54.814 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:07:58.724 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [ERROR] 2024-05-07 17:08:00.662 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:00.703 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:05.728 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:10.747 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:15.766 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:20.806 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:25.858 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:30.879 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:35.912 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1102][TI-4003] - [INFO] 2024-05-07 17:08:39.742 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [WARN] 2024-05-07 17:08:39.744 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:40.934 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:45.953 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:50.970 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:08:55.983 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:01.001 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:06.012 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:09:06.747 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:11.025 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:16.044 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:21.065 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:26.089 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:31.122 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:36.136 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:41.147 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:41.900 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:09:41.900 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-1100][TI-4001] - [INFO] 2024-05-07 17:09:42.901 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [WARN] 2024-05-07 17:09:42.902 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:46.202 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:50.923 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:51.237 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:09:56.257 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1111][TI-4011] - [INFO] 2024-05-07 17:09:57.964 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-0][TI-0] - [WARN] 2024-05-07 17:09:57.965 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-1109][TI-4010] - [INFO] 2024-05-07 17:09:58.976 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-0][TI-0] - [WARN] 2024-05-07 17:09:58.977 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-1110][TI-4012] - [INFO] 2024-05-07 17:09:58.983 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [WARN] 2024-05-07 17:09:58.983 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:01.268 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:06.279 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:09.396 +0800 o.a.d.s.m.s.MasterFailoverService:[86] - Master failover service 172.18.0.14:5678 begin to failover hosts:[172.18.0.14:5678]
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:09.426 +0800 o.a.d.s.m.s.MasterFailoverService:[124] - Master[172.18.0.14:5678] failover starting there are 4 workflowInstance may need to failover, will do a deep check, workflowInstanceIds: [448, 508, 510, 511]
[WI-448][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-448][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-508][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-508][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-510][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-510][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-511][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-511][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:09.427 +0800 o.a.d.s.m.s.MasterFailoverService:[148] - Master[172.18.0.14:5678] failover finished, useTime:5ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:11.303 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:10:14.805 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:16.325 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:21.346 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:26.364 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:31.388 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:36.413 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:41.435 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:46.459 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:51.476 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1108][TI-4009] - [INFO] 2024-05-07 17:10:52.157 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [WARN] 2024-05-07 17:10:52.157 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [INFO] 2024-05-07 17:10:56.504 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:01.520 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 8/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:06.547 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:09.240 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:11:09.240 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:11.571 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:15.285 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:16.595 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:21.607 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:11:22.879 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:26.686 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:29.332 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:31.715 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:36.729 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1101][TI-4002] - [INFO] 2024-05-07 17:11:41.332 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [WARN] 2024-05-07 17:11:41.333 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:41.384 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:41.741 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:46.757 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1106][TI-4007] - [INFO] 2024-05-07 17:11:49.351 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [WARN] 2024-05-07 17:11:49.351 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:51.772 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:56.793 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 10/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:11:57.516 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:11:57.516 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [ERROR] 2024-05-07 17:12:00.665 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:01.805 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:06.818 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:07.554 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:11.844 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:16.866 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:21.882 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:26.905 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:12:30.945 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:31.924 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:36.940 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:41.956 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:46.969 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1107][TI-4008] - [INFO] 2024-05-07 17:12:47.495 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [WARN] 2024-05-07 17:12:47.495 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-1103][TI-4004] - [INFO] 2024-05-07 17:12:48.510 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-0][TI-0] - [WARN] 2024-05-07 17:12:48.510 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-1105][TI-4005] - [INFO] 2024-05-07 17:12:48.513 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-0][TI-0] - [WARN] 2024-05-07 17:12:48.514 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-1104][TI-4006] - [INFO] 2024-05-07 17:12:48.515 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [WARN] 2024-05-07 17:12:48.515 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:48.824 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 0.7507163323782235 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:48.825 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 0.7507163323782235 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:12:48.825 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:52.011 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:12:57.038 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:02.082 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:07.094 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:12.112 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:17.149 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:22.165 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:27.179 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:32.204 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:37.239 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:13:38.973 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-1102][TI-4003] - [INFO] 2024-05-07 17:13:40.676 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [WARN] 2024-05-07 17:13:40.677 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:42.258 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:47.306 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:52.318 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:13:57.355 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:02.366 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:07.391 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:12.427 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:17.450 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 4/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:22.474 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:27.490 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:32.517 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:37.529 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:42.547 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-1100][TI-4001] - [INFO] 2024-05-07 17:14:42.925 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [WARN] 2024-05-07 17:14:42.926 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [ERROR] 2024-05-07 17:14:47.020 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:47.575 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:52.599 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:14:57.623 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-1111][TI-4011] - [INFO] 2024-05-07 17:14:58.964 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-0][TI-0] - [WARN] 2024-05-07 17:14:58.965 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-1109][TI-4010] - [INFO] 2024-05-07 17:14:59.968 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-0][TI-0] - [WARN] 2024-05-07 17:14:59.969 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-1110][TI-4012] - [INFO] 2024-05-07 17:14:59.973 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [WARN] 2024-05-07 17:14:59.974 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:02.637 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:07.659 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:12.671 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:17.682 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:22.694 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:27.706 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:32.847 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:37.873 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:42.906 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:47.917 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:52.932 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1108][TI-4009] - [INFO] 2024-05-07 17:15:53.145 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [WARN] 2024-05-07 17:15:53.145 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [ERROR] 2024-05-07 17:15:55.174 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:57.185 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:15:57.943 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:16:00.670 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:02.956 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:07.975 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:12.989 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:17.693 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [WARN] 2024-05-07 17:16:17.693 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[123] - The current server is overload, cannot consumes commands.
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:18.003 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:23.023 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:28.037 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:33.066 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:37.768 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.5 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:38.090 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-1101][TI-4002] - [INFO] 2024-05-07 17:16:41.770 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [WARN] 2024-05-07 17:16:41.775 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:43.107 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:48.123 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1106][TI-4007] - [INFO] 2024-05-07 17:16:49.801 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [WARN] 2024-05-07 17:16:49.804 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:53.143 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:16:58.160 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:03.176 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:17:03.210 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:08.201 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:13.225 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:18.243 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:20.933 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 2.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:23.255 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:28.278 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:33.328 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:38.341 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:39.997 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:43.357 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1107][TI-4008] - [INFO] 2024-05-07 17:17:47.957 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [WARN] 2024-05-07 17:17:47.958 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:48.381 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1103][TI-4004] - [INFO] 2024-05-07 17:17:48.961 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-0][TI-0] - [WARN] 2024-05-07 17:17:48.962 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-1105][TI-4005] - [INFO] 2024-05-07 17:17:48.964 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-0][TI-0] - [WARN] 2024-05-07 17:17:48.964 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-1104][TI-4006] - [INFO] 2024-05-07 17:17:48.972 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [WARN] 2024-05-07 17:17:48.972 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:53.393 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:17:58.409 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:03.425 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:08.444 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:18:11.253 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:13.468 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:18.491 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:23.509 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:28.527 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:33.561 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:38.581 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1102][TI-4003] - [INFO] 2024-05-07 17:18:41.141 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [WARN] 2024-05-07 17:18:41.142 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:43.594 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:48.606 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:53.622 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:18:58.635 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:03.273 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:03.665 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:04.234 +0800 o.a.d.s.m.r.MasterSlotManager:[90] - Current master is not in active master list
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:04.275 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:05.278 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:06.279 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:07.284 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:08.286 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:08.688 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:09.288 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:10.292 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:11.293 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:12.295 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:13.297 +0800 o.a.d.s.m.r.MasterSchedulerBootstrap:[179] - Master count: 0 is invalid, the current slot: 0
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:13.707 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:14.259 +0800 o.a.d.s.m.r.MasterSlotManager:[94] - Update master nodes, total master size: 1, current slot: 0
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:18.718 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:19:19.303 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:23.734 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:28.759 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:33.794 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:38.808 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1100][TI-4001] - [INFO] 2024-05-07 17:19:43.273 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:43.275 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4001, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 14:20:23 GMT+08:00 2024, endTime=Tue May 07 14:20:41 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_4/1100/4001, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/4/1100/4001.log, processId=103, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1100)
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:43.840 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 11/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:48.875 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:53.897 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:19:58.910 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1111][TI-4011] - [INFO] 2024-05-07 17:19:59.444 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-0][TI-0] - [WARN] 2024-05-07 17:19:59.445 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4011, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:54 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1111/4011, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1111/4011.log, processId=2579, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1111)
[WI-1109][TI-4010] - [INFO] 2024-05-07 17:20:00.455 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-0][TI-0] - [WARN] 2024-05-07 17:20:00.456 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4010, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1109/4010, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1109/4010.log, processId=2580, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1109)
[WI-1110][TI-4012] - [INFO] 2024-05-07 17:20:00.458 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [WARN] 2024-05-07 17:20:00.458 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4012, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:49:48 GMT+08:00 2024, endTime=Tue May 07 16:49:55 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_10/1110/4012, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/10/1110/4012.log, processId=2578, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1110)
[WI-0][TI-0] - [ERROR] 2024-05-07 17:20:00.673 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:03.930 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:08.958 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:09.434 +0800 o.a.d.s.m.s.MasterFailoverService:[86] - Master failover service 172.18.0.14:5678 begin to failover hosts:[172.18.0.14:5678]
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[124] - Master[172.18.0.14:5678] failover starting there are 4 workflowInstance may need to failover, will do a deep check, workflowInstanceIds: [448, 508, 510, 511]
[WI-448][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-448][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-508][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-508][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-510][TI-0] - [INFO] 2024-05-07 17:20:09.473 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-510][TI-0] - [INFO] 2024-05-07 17:20:09.474 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-511][TI-0] - [INFO] 2024-05-07 17:20:09.474 +0800 o.a.d.s.m.s.MasterFailoverService:[133] - WorkflowInstance failover starting
[WI-511][TI-0] - [INFO] 2024-05-07 17:20:09.474 +0800 o.a.d.s.m.s.MasterFailoverService:[190] - The workflowInstance's restartTime is after the dead master startup time, no need to failover
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:09.474 +0800 o.a.d.s.m.s.MasterFailoverService:[148] - Master[172.18.0.14:5678] failover finished, useTime:5ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:13.976 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:18.988 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:24.005 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:20:27.376 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:29.017 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:34.036 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:39.052 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:44.072 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:49.084 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1108][TI-4009] - [INFO] 2024-05-07 17:20:53.914 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [WARN] 2024-05-07 17:20:53.916 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4009, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:05:45 GMT+08:00 2024, endTime=Tue May 07 16:05:46 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_9/1108/4009, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/9/1108/4009.log, processId=2003, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1108)
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:54.094 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:20:59.114 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:04.153 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:09.168 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:14.184 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:19.202 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:21.005 +0800 o.a.d.s.m.c.MasterServerLoadProtection:[48] - Master OverLoad: the TotalCpuUsedPercentage: 1.0 is over then the MaxCpuUsagePercentageThresholds 0.7
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:24.247 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:29.272 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:34.297 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:21:35.482 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:39.323 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1101][TI-4002] - [INFO] 2024-05-07 17:21:42.919 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [WARN] 2024-05-07 17:21:42.921 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4002, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:46:32 GMT+08:00 2024, endTime=Tue May 07 15:46:33 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1101/4002, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1101/4002.log, processId=1302, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1101)
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:44.336 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:49.374 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1106][TI-4007] - [INFO] 2024-05-07 17:21:49.942 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [WARN] 2024-05-07 17:21:49.942 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4007, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:56:27 GMT+08:00 2024, endTime=Tue May 07 15:56:42 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_7/1106/4007, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/7/1106/4007.log, processId=1711, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1106)
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:54.385 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:21:59.409 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:04.439 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:09.467 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:14.484 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:19.500 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:24.512 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:29.535 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:34.566 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:39.583 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:22:43.522 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:44.603 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-1107][TI-4008] - [INFO] 2024-05-07 17:22:48.151 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-0][TI-0] - [WARN] 2024-05-07 17:22:48.154 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4008, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 16:02:32 GMT+08:00 2024, endTime=Tue May 07 16:02:39 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_8/1107/4008, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/8/1107/4008.log, processId=1874, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1107)
[WI-1103][TI-4004] - [INFO] 2024-05-07 17:22:49.165 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-0][TI-0] - [WARN] 2024-05-07 17:22:49.167 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4004, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1103/4004, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1103/4004.log, processId=1525, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1103)
[WI-1105][TI-4005] - [INFO] 2024-05-07 17:22:49.169 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-0][TI-0] - [WARN] 2024-05-07 17:22:49.169 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4005, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1105/4005, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1105/4005.log, processId=1543, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1105)
[WI-1104][TI-4006] - [INFO] 2024-05-07 17:22:49.172 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [WARN] 2024-05-07 17:22:49.173 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4006, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:52:33 GMT+08:00 2024, endTime=Tue May 07 15:52:38 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_6/1104/4006, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/6/1104/4006.log, processId=1537, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1104)
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:49.615 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:54.679 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:22:59.696 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:04.739 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:09.756 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 3/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:14.772 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:19.791 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:24.812 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 2/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:29.830 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:34.850 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:39.865 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-1102][TI-4003] - [INFO] 2024-05-07 17:23:41.924 +0800 o.a.d.s.m.r.l.TaskInstanceExecutionResultEventListenFunction:[45] - Received TaskInstanceExecutionFinishEvent: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [WARN] 2024-05-07 17:23:41.925 +0800 o.a.d.s.m.p.q.TaskExecuteThreadPool:[85] - Cannot find workflowExecuteThread from cacheManager, event: TaskEvent(taskInstanceId=4003, workerAddress=172.18.1.1:1234, state=TaskExecutionStatus{code=6, desc='failure'}, startTime=Tue May 07 15:48:00 GMT+08:00 2024, endTime=Tue May 07 15:48:28 GMT+08:00 2024, executePath=/tmp/dolphinscheduler/exec/process/default/13001194483488/13520356270336_5/1102/4003, logPath=/opt/dolphinscheduler/logs/20240507/13520356270336/5/1102/4003.log, processId=1336, appIds=, event=RESULT, varPool=[], cacheTaskInstanceId=0, processInstanceId=1102)
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:44.879 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:49.892 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 0/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:23:51.618 +0800 o.s.s.q.LocalDataSourceJobStore:[3941] - ClusterManager: Error managing cluster: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_locks" does not exist
  Position: 15
	... 14 common frames omitted
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:54.930 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 7/ms
[WI-0][TI-0] - [INFO] 2024-05-07 17:23:59.962 +0800 o.a.d.s.m.r.t.TaskGroupCoordinator:[127] - TaskGroupCoordinator round time cost: 1/ms
[WI-0][TI-0] - [ERROR] 2024-05-07 17:24:00.694 +0800 o.s.s.q.LocalDataSourceJobStore:[4017] - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
	... 2 common frames omitted
